### ISSUE TITLE
bug: CI/CD workflow fails if user doesn't have access to model artifacts from other deployments

### ISSUE THREAD

**Issue by mpkrass7** [datarobot-oss/custom-models-action#309]
https://github.com/datarobot-oss/custom-models-action/blob/992719a747b66dbe1d130587f8b9c6f41633f819/src/deployment_controller.py#L100

It looks like CI/CD workflows fail if you have access to a deployment but not its corresponding model artifacts. So if one of my peers builds a model outside of DataRobot and shares the deployment with me, my CI/CD workflow for an unrelated deployment will fail due to the check in the above function

**Comment by zohar-mizrahi** [comment]
This issue is solved with the new namespace functionality:
* If the shared deployment was created from a different repository, than by default it'll be assigned to a different namespace and consequently will not be processed by the other repository.
* If is it from the same repository, but different branches, than it is expected that each branch will configure its own namespace, thus making sure the entities will be created in an isolated namespace.
